version: "3"
services:
  loadbalancer:
    image: nginx:stable
    volumes:
      - "./nginx.conf.template:/etc/nginx/templates/nginx.conf.template"
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=booklet.localhost
      - NGINX_RAILS_HOST=${NGINX_PROXY_RAILS:-rails}
      - NGINX_PORT=80
    depends_on:
      - nuxt
#      - rails
    networks:
      - seven_booklet
    extra_hosts:
      - "host.docker.internal:host-gateway"


networks:
  seven_booklet:
    driver: bridge
