
version: "3"
services:
    sidekiq:
      build:
        context: booklet.byseven.co
      volumes:
        - "./booklet.byseven.co:/app"
        - "/app/tmp"

    rails:
      build:
        context: booklet.byseven.co
      volumes:
        - "./booklet.byseven.co:/app"
        - "/app/tmp"

    webpack:
      build:
        context: booklet.byseven.co
      volumes:
        - "./booklet.byseven.co:/app"
        - "/app/tmp"

